name: Activity 2 workflow
on: push

jobs:
  build: 
    name: Starts read secrets
    runs on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./actions/
      - run: npm i
      - run: node activity2.js
        env:
          NAME: ${{NAME_SECRET}}
          AGE:  ${{AGE_SECRET}}
          YEAR: "0"