name: Activity2 Github Action

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use activity2.js ${{ matrix.node-version }}
      uses: ./actions
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: node activity2.js

  
