name: Activity2 Github Action

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Starts Activity2 action
    
    steps:
    - uses: actions/checkout@v1
    - uses: ./actions
      with:
        node-version: 12
        NAME: ${{ secrets.NAME_SECRET }}
        AGE: ${{ secrets.AGE_SECRET }}
        YEAR: "0"
    - run: npm install    
    - run: echo "Working hopefully"



  
