name: Activity2 Github Action

on:
  push:

jobs:
  build:
    name: Starts Activity2 action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./actions
      env:
        NAME: ${{ secrets.NAME_SECRET }}
        AGE: ${{ secrets.AGE_SECRET }}
        YEAR: "0"
  
    - run: echo your age ${{ secrets.AGE_SECRET  }}

  
